version: '3.9'
services:
  db:
    image: postgres:15
    container_name: voting_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123456789
      POSTGRES_DB: votes
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
